name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run MySQL service
        run: |
          echo "version: '3.8'
          services:
          mysql:
           image: mysql:8.0
           ports:
             - 3306:3306
           environment:
             - MYSQL_ROOT_PASSWORD=root
             - MYSQL_DATABASE=your_database_name
             - MYSQL_USER=your_username
             - MYSQL_PASSWORD=your_password" 
             - MYSQL_HOST=localhost
             - MYSQL_PORT=3306

      - name: Build with Maven
        run: mvn clean install

